"""Adopt the fixture, provider-map and market-cache tables from algo.

State only. db_table stays algo_*, so no data moves and every index keeps
its existing name.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algo', '0037_move_to_catalog_and_scoring'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Nothing reaches the database. These tables already exist in
            # production, and on a fresh build algo's historical migrations
            # create them, so this only moves ownership in migration state.
            database_operations=[],
            state_operations=[

                migrations.CreateModel(
                    name='BookmakerLeagueMap',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('provider', models.CharField(max_length=30)),
                        ('provider_competition_id', models.CharField(blank=True, max_length=100)),
                        ('provider_competition_name', models.CharField(max_length=255)),
                        ('provider_competition_normalized', models.CharField(blank=True, max_length=255)),
                        ('api_league_id', models.PositiveIntegerField()),
                        ('api_league_name', models.CharField(blank=True, max_length=255)),
                        ('country', models.CharField(blank=True, max_length=100)),
                        ('current_api_season', models.PositiveIntegerField(blank=True, null=True)),
                        ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                        ('active', models.BooleanField(default=True)),
                        ('source', models.CharField(default='auto', max_length=50)),
                        ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'algo_bookmakerleaguemap',
                        'ordering': ['provider', 'provider_competition_name'],
                        'indexes': [models.Index(fields=['provider', 'provider_competition_id'], name='algo_bookma_provide_018943_idx'), models.Index(fields=['provider', 'provider_competition_normalized'], name='algo_bookma_provide_d3f2ec_idx'), models.Index(fields=['api_league_id'], name='algo_bookma_api_lea_44fdcd_idx'), models.Index(fields=['active'], name='algo_bookma_active_89139c_idx')],
                        'constraints': [models.UniqueConstraint(fields=('provider', 'provider_competition_id', 'provider_competition_normalized'), name='unique_bookmaker_league_map_provider_competition')],
                    },
                ),
                migrations.CreateModel(
                    name='FixtureCache',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('match_date', models.DateField()),
                        ('fixture', models.CharField(max_length=255)),
                        ('home_team', models.CharField(blank=True, max_length=255)),
                        ('away_team', models.CharField(blank=True, max_length=255)),
                        ('home_team_normalized', models.CharField(blank=True, max_length=255)),
                        ('away_team_normalized', models.CharField(blank=True, max_length=255)),
                        ('fixture_normalized', models.CharField(blank=True, max_length=520)),
                        ('home_logo', models.URLField(blank=True)),
                        ('away_logo', models.URLField(blank=True)),
                        ('league', models.CharField(blank=True, max_length=255)),
                        ('league_logo', models.URLField(blank=True)),
                        ('country', models.CharField(blank=True, max_length=100)),
                        ('country_flag', models.URLField(blank=True)),
                        ('round', models.CharField(blank=True, max_length=255)),
                        ('league_type', models.CharField(blank=True, max_length=50)),
                        ('kickoff', models.CharField(blank=True, max_length=50)),
                        ('kickoff_utc', models.DateTimeField(blank=True, null=True)),
                        ('match_id', models.CharField(max_length=100, unique=True)),
                        ('api_payload', models.JSONField(blank=True, default=dict)),
                        ('source', models.CharField(default='api_football', max_length=30)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'algo_fixturecache',
                        'ordering': ['match_date', 'country', 'league', 'kickoff', 'fixture'],
                        'indexes': [models.Index(fields=['match_date'], name='algo_fixtur_match_d_c01942_idx'), models.Index(fields=['home_team_normalized'], name='algo_fixtur_home_te_063e0e_idx'), models.Index(fields=['away_team_normalized'], name='algo_fixtur_away_te_2d86bb_idx'), models.Index(fields=['fixture_normalized'], name='algo_fixtur_fixture_d3bf86_idx'), models.Index(fields=['country', 'league'], name='algo_fixtur_country_7456b5_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='StatPalFixtureCoverage',
                    fields=[
                    ],
                    options={
                        'verbose_name': 'StatPal Fixture Coverage',
                        'verbose_name_plural': 'StatPal Fixture Coverage',
                        'proxy': True,
                        'indexes': [],
                        'constraints': [],
                    },
                    bases=('catalog.fixturecache',),
                ),
                migrations.CreateModel(
                    name='ProviderFixtureMap',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('provider', models.CharField(max_length=30)),
                        ('provider_event_id', models.CharField(max_length=120)),
                        ('provider_competition_id', models.CharField(blank=True, max_length=100)),
                        ('provider_competition_name', models.CharField(blank=True, max_length=255)),
                        ('api_fixture_id', models.CharField(max_length=100)),
                        ('api_league_id', models.PositiveIntegerField(blank=True, null=True)),
                        ('api_league_name', models.CharField(blank=True, max_length=255)),
                        ('provider_home_team', models.CharField(blank=True, max_length=255)),
                        ('provider_away_team', models.CharField(blank=True, max_length=255)),
                        ('api_home_team', models.CharField(blank=True, max_length=255)),
                        ('api_away_team', models.CharField(blank=True, max_length=255)),
                        ('kickoff_at', models.DateTimeField(blank=True, null=True)),
                        ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                        ('resolution_method', models.CharField(default='team_date_league', max_length=80)),
                        ('active', models.BooleanField(default=True)),
                        ('payload', models.JSONField(blank=True, default=dict)),
                        ('verified_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'algo_providerfixturemap',
                        'ordering': ['provider', 'provider_event_id'],
                        'indexes': [models.Index(fields=['provider', 'provider_event_id'], name='algo_provid_provide_48016a_idx'), models.Index(fields=['api_fixture_id'], name='algo_provid_api_fix_877336_idx'), models.Index(fields=['provider_competition_id'], name='algo_provid_provide_af8d6e_idx'), models.Index(fields=['active'], name='algo_provid_active_16b984_idx')],
                        'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_provider_fixture_map_event')],
                    },
                ),
                migrations.CreateModel(
                    name='ProviderPlayerMap',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('provider', models.CharField(max_length=30)),
                        ('provider_player_id', models.CharField(max_length=120)),
                        ('provider_player_name', models.CharField(max_length=255)),
                        ('provider_player_normalized', models.CharField(blank=True, max_length=255)),
                        ('internal_player_id', models.CharField(blank=True, max_length=120)),
                        ('internal_player_name', models.CharField(blank=True, max_length=255)),
                        ('internal_player_normalized', models.CharField(blank=True, max_length=255)),
                        ('provider_team_id', models.CharField(blank=True, max_length=120)),
                        ('provider_team_name', models.CharField(blank=True, max_length=255)),
                        ('internal_team_id', models.CharField(blank=True, max_length=120)),
                        ('internal_team_name', models.CharField(blank=True, max_length=255)),
                        ('position', models.CharField(blank=True, max_length=80)),
                        ('nationality', models.CharField(blank=True, max_length=100)),
                        ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                        ('resolution_method', models.CharField(default='provider_id', max_length=80)),
                        ('active', models.BooleanField(default=True)),
                        ('payload', models.JSONField(blank=True, default=dict)),
                        ('verified_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'algo_providerplayermap',
                        'ordering': ['provider', 'provider_player_name'],
                        'indexes': [models.Index(fields=['provider', 'provider_player_id'], name='algo_provid_provide_6ced3d_idx'), models.Index(fields=['provider', 'provider_player_normalized'], name='algo_provid_provide_01c6dd_idx'), models.Index(fields=['internal_player_id'], name='algo_provid_interna_c2567c_idx'), models.Index(fields=['provider_team_id'], name='algo_provid_provide_1db07c_idx'), models.Index(fields=['active'], name='algo_provid_active_1c4270_idx')],
                        'constraints': [models.UniqueConstraint(fields=('provider', 'provider_player_id'), name='unique_provider_player_map_provider_player')],
                    },
                ),
                migrations.CreateModel(
                    name='ProviderTeamMap',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('provider', models.CharField(max_length=30)),
                        ('provider_team_id', models.CharField(max_length=120)),
                        ('provider_team_name', models.CharField(max_length=255)),
                        ('provider_team_normalized', models.CharField(blank=True, max_length=255)),
                        ('internal_team_id', models.CharField(blank=True, max_length=120)),
                        ('internal_team_name', models.CharField(blank=True, max_length=255)),
                        ('internal_team_normalized', models.CharField(blank=True, max_length=255)),
                        ('api_team_id', models.PositiveIntegerField(blank=True, null=True)),
                        ('country', models.CharField(blank=True, max_length=100)),
                        ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                        ('resolution_method', models.CharField(default='provider_id', max_length=80)),
                        ('active', models.BooleanField(default=True)),
                        ('payload', models.JSONField(blank=True, default=dict)),
                        ('verified_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'algo_providerteammap',
                        'ordering': ['provider', 'provider_team_name'],
                        'indexes': [models.Index(fields=['provider', 'provider_team_id'], name='algo_provid_provide_127630_idx'), models.Index(fields=['provider', 'provider_team_normalized'], name='algo_provid_provide_8b6700_idx'), models.Index(fields=['internal_team_id'], name='algo_provid_interna_59c9e2_idx'), models.Index(fields=['api_team_id'], name='algo_provid_api_tea_f485fe_idx'), models.Index(fields=['active'], name='algo_provid_active_20ff1d_idx')],
                        'constraints': [models.UniqueConstraint(fields=('provider', 'provider_team_id'), name='unique_provider_team_map_provider_team')],
                    },
                ),
                migrations.CreateModel(
                    name='SlipReviewMarketCache',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('cache_scope', models.CharField(choices=[('slip_review', 'Slip Review')], default='slip_review', max_length=30)),
                        ('source', models.CharField(choices=[('statpal', 'StatPal'), ('api_football', 'API-Football'), ('merged', 'Merged'), ('on_demand', 'On Demand')], default='merged', max_length=30)),
                        ('match_date', models.DateField()),
                        ('fixture', models.CharField(max_length=255)),
                        ('home_team', models.CharField(blank=True, max_length=255)),
                        ('away_team', models.CharField(blank=True, max_length=255)),
                        ('home_logo', models.URLField(blank=True)),
                        ('away_logo', models.URLField(blank=True)),
                        ('league', models.CharField(blank=True, max_length=255)),
                        ('league_id', models.CharField(blank=True, max_length=100)),
                        ('league_logo', models.URLField(blank=True)),
                        ('country', models.CharField(blank=True, max_length=100)),
                        ('country_flag', models.URLField(blank=True)),
                        ('kickoff', models.CharField(blank=True, max_length=50)),
                        ('match_id', models.CharField(max_length=100)),
                        ('provider_match_id', models.CharField(blank=True, max_length=120)),
                        ('provider_competition_id', models.CharField(blank=True, max_length=120)),
                        ('home_team_id', models.CharField(blank=True, max_length=120)),
                        ('away_team_id', models.CharField(blank=True, max_length=120)),
                        ('market', models.CharField(max_length=120)),
                        ('market_family', models.CharField(blank=True, max_length=80)),
                        ('meaning', models.CharField(blank=True, max_length=255)),
                        ('raw_confidence', models.PositiveIntegerField(default=0)),
                        ('confidence', models.PositiveIntegerField(default=0)),
                        ('final_confidence', models.FloatField(blank=True, null=True)),
                        ('odds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                        ('ev', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                        ('odds_source', models.CharField(blank=True, max_length=30)),
                        ('odds_meta', models.JSONField(blank=True, default=dict)),
                        ('eligible', models.BooleanField(default=False)),
                        ('risk_flags', models.JSONField(blank=True, default=list)),
                        ('insights', models.JSONField(blank=True, default=dict)),
                        ('market_payload', models.JSONField(blank=True, default=dict)),
                        ('fixture_payload', models.JSONField(blank=True, default=dict)),
                        ('provider_merge', models.JSONField(blank=True, default=dict)),
                        ('data_quality', models.CharField(blank=True, max_length=30)),
                        ('cache_version', models.CharField(blank=True, max_length=40)),
                        ('expires_at', models.DateTimeField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'algo_slipreviewmarketcache',
                        'ordering': ['match_date', 'fixture', '-confidence', 'market'],
                        'indexes': [models.Index(fields=['cache_scope', 'match_date'], name='algo_slipre_cache_s_74efeb_idx'), models.Index(fields=['cache_scope', 'match_id', 'market'], name='algo_slipre_cache_s_d499d7_idx'), models.Index(fields=['cache_scope', 'provider_match_id', 'market'], name='algo_slipre_cache_s_d5beaa_idx'), models.Index(fields=['cache_scope', 'league_id', 'match_date'], name='algo_slipre_cache_s_2aaf55_idx'), models.Index(fields=['cache_scope', 'market_family', 'confidence'], name='algo_slipre_cache_s_e2d33d_idx'), models.Index(fields=['expires_at'], name='algo_slipre_expires_88da06_idx')],
                        'constraints': [models.UniqueConstraint(fields=('cache_scope', 'match_id', 'market'), name='unique_slip_review_market_cache_match_market')],
                    },
                ),
                migrations.CreateModel(
                    name='TeamAliasMap',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('provider', models.CharField(blank=True, max_length=30)),
                        ('api_team_id', models.PositiveIntegerField(blank=True, null=True)),
                        ('canonical_name', models.CharField(max_length=255)),
                        ('canonical_normalized', models.CharField(blank=True, max_length=255)),
                        ('alias', models.CharField(max_length=255)),
                        ('alias_normalized', models.CharField(max_length=255)),
                        ('country', models.CharField(blank=True, max_length=100)),
                        ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                        ('active', models.BooleanField(default=True)),
                        ('source', models.CharField(default='auto', max_length=50)),
                        ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'algo_teamaliasmap',
                        'ordering': ['alias'],
                        'indexes': [models.Index(fields=['provider', 'alias_normalized'], name='algo_teamal_provide_37fb06_idx'), models.Index(fields=['api_team_id'], name='algo_teamal_api_tea_60eb71_idx'), models.Index(fields=['canonical_normalized'], name='algo_teamal_canonic_857422_idx'), models.Index(fields=['active'], name='algo_teamal_active_3d3ef8_idx')],
                        'constraints': [models.UniqueConstraint(fields=('provider', 'alias_normalized', 'canonical_normalized'), name='unique_team_alias_provider_alias_canonical')],
                    },
                ),
                migrations.CreateModel(
                    name='StatPalFixtureSnapshot',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('match_id', models.CharField(blank=True, max_length=120)),
                        ('provider_match_id', models.CharField(blank=True, max_length=120)),
                        ('provider_competition_id', models.CharField(blank=True, max_length=100)),
                        ('snapshot_type', models.CharField(choices=[('injuries_suspensions', 'Injuries & Suspensions'), ('team_stats', 'Team Stats'), ('prematch_odds', 'Pre-Match Odds'), ('live_odds', 'Live Odds'), ('lineups', 'Lineups'), ('predictions', 'Predictions'), ('detailed_stats', 'Detailed Stats'), ('head_to_head', 'Head to Head'), ('league_standings', 'League Standings'), ('league_stats', 'League Stats'), ('weather_forecast', 'Weather Forecast'), ('player_stats', 'Player Stats'), ('coach', 'Coach'), ('images', 'Images'), ('live_storylines', 'Live Storylines'), ('raw', 'Raw')], max_length=40)),
                        ('source_endpoint', models.CharField(blank=True, max_length=160)),
                        ('status', models.CharField(default='available', max_length=30)),
                        ('payload', models.JSONField(blank=True, default=dict)),
                        ('summary', models.JSONField(blank=True, default=dict)),
                        ('fetched_at', models.DateTimeField(blank=True, null=True)),
                        ('expires_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statpal_snapshots', to='catalog.fixturecache')),
                        ('provider_fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statpal_snapshots', to='catalog.providerfixturemap')),
                    ],
                    options={
                        'db_table': 'algo_statpalfixturesnapshot',
                        'ordering': ['-fetched_at', '-updated_at'],
                        'indexes': [models.Index(fields=['match_id', 'snapshot_type'], name='algo_statpa_match_i_d90ef4_idx'), models.Index(fields=['provider_match_id', 'snapshot_type'], name='algo_statpa_provide_46898f_idx'), models.Index(fields=['provider_competition_id', 'snapshot_type'], name='algo_statpa_provide_575a02_idx'), models.Index(fields=['snapshot_type', 'status'], name='algo_statpa_snapsho_5fc3c0_idx'), models.Index(fields=['expires_at'], name='algo_statpa_expires_391f29_idx')],
                        'constraints': [models.UniqueConstraint(fields=('match_id', 'provider_match_id', 'snapshot_type'), name='unique_statpal_snapshot_fixture_type')],
                    },
                ),
            ],
        ),
    ]
