# Generated by Django 5.2.13 on 2026-09-09 22:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_leaguemarketprofile_teamprofile_teammarketprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255)),
                ('canonical_normalized', models.CharField(db_index=True, max_length=255)),
                ('provider', models.CharField(default='statpal', max_length=30)),
                ('provider_coach_id', models.CharField(blank=True, max_length=120)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('research_status', models.CharField(choices=[('unresearched', 'Unresearched'), ('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('stale', 'Stale')], default='unresearched', max_length=20)),
                ('research_confidence', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='unknown', max_length=20)),
                ('research_sources', models.JSONField(blank=True, default=list)),
                ('research_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_coach_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_coachprofile',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='CoachTacticalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('preferred_formation', models.CharField(blank=True, max_length=40)),
                ('alternative_formations', models.JSONField(blank=True, default=list)),
                ('philosophy_summary', models.TextField(blank=True)),
                ('attacking_style', models.CharField(blank=True, max_length=120)),
                ('defensive_style', models.CharField(blank=True, max_length=120)),
                ('build_up_style', models.CharField(blank=True, max_length=120)),
                ('leading_approach', models.TextField(blank=True)),
                ('trailing_approach', models.TextField(blank=True)),
                ('attacking_notes', models.TextField(blank=True)),
                ('defensive_notes', models.TextField(blank=True)),
                ('match_management_notes', models.TextField(blank=True)),
                ('set_piece_notes', models.TextField(blank=True)),
                ('possession_tendency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('build_up_patience', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passing_directness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attacking_tempo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attacking_width', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('crossing_tendency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('counterattack_tendency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attacking_risk', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pressing_intensity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('defensive_block_height', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('defensive_line_height', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('defensive_compactness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('transition_defence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('defensive_aggression', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('set_piece_emphasis', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rotation_tendency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tactical_flexibility', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('youth_usage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='unknown', max_length=20)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('research_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_profiles', to='catalog.coachprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coach_tactical_profiles', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_coach_tactical_profiles', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text="Leave blank for the coach's general philosophy; select a team for a club-specific implementation.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_tactical_profiles', to='catalog.teamprofile')),
            ],
            options={
                'db_table': 'catalog_coachtacticalprofile',
                'ordering': ['coach__canonical_name', '-version', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamCoachAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('permanent', 'Permanent'), ('interim', 'Interim'), ('caretaker', 'Caretaker'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('date_precision', models.CharField(choices=[('confirmed', 'Confirmed'), ('estimated', 'Estimated'), ('detected', 'First detected')], default='detected', max_length=20)),
                ('currently_active', models.BooleanField(default=True)),
                ('change_reason', models.CharField(blank=True, max_length=80)),
                ('provider', models.CharField(default='statpal', max_length=30)),
                ('provider_team_id', models.CharField(blank=True, max_length=120)),
                ('provider_coach_id', models.CharField(blank=True, max_length=120)),
                ('provider_team_name', models.CharField(blank=True, max_length=255)),
                ('provider_coach_name', models.CharField(blank=True, max_length=255)),
                ('first_detected_at', models.DateTimeField()),
                ('last_confirmed_at', models.DateTimeField()),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_assignments', to='catalog.coachprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='catalog.teamprofile')),
            ],
            options={
                'db_table': 'catalog_teamcoachassignment',
                'ordering': ['-currently_active', 'team__canonical_name', '-first_detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['provider', 'provider_coach_id'], name='catalog_coa_provide_3c1ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['research_status', 'active'], name='catalog_coa_researc_a8e255_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_coach_id', ''), _negated=True), fields=('provider', 'provider_coach_id'), name='unique_catalog_provider_coach'),
        ),
        migrations.AddIndex(
            model_name='coachtacticalprofile',
            index=models.Index(fields=['status', 'confidence'], name='catalog_coa_status_fa404c_idx'),
        ),
        migrations.AddIndex(
            model_name='coachtacticalprofile',
            index=models.Index(fields=['coach', 'team', 'status'], name='catalog_coa_coach_i_f9ce4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachtacticalprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('coach', 'version'), name='unique_general_coach_tactical_version'),
        ),
        migrations.AddConstraint(
            model_name='coachtacticalprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('coach', 'team', 'version'), name='unique_team_coach_tactical_version'),
        ),
        migrations.AddIndex(
            model_name='teamcoachassignment',
            index=models.Index(fields=['currently_active', 'last_confirmed_at'], name='catalog_tea_current_d24f84_idx'),
        ),
        migrations.AddIndex(
            model_name='teamcoachassignment',
            index=models.Index(fields=['provider', 'provider_team_id'], name='catalog_tea_provide_52b191_idx'),
        ),
        migrations.AddIndex(
            model_name='teamcoachassignment',
            index=models.Index(fields=['provider', 'provider_coach_id'], name='catalog_tea_provide_a53442_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamcoachassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('currently_active', True)), fields=('team',), name='unique_current_coach_per_team'),
        ),
    ]
