# Generated by Django 5.2.13 on 2026-09-10 13:46

import django.core.validators
from django.db import migrations, models

RATING_FIELDS = (
    "possession_tendency",
    "build_up_patience",
    "passing_directness",
    "attacking_tempo",
    "attacking_width",
    "crossing_tendency",
    "counterattack_tendency",
    "attacking_risk",
    "pressing_intensity",
    "defensive_block_height",
    "defensive_line_height",
    "defensive_compactness",
    "transition_defence",
    "defensive_aggression",
    "set_piece_emphasis",
    "rotation_tendency",
    "tactical_flexibility",
    "youth_usage",
)
NARRATIVE_TARGETS = {
    "philosophy_summary": 160,
    "attacking_style": 40,
    "defensive_style": 40,
    "build_up_style": 40,
    "leading_approach": 80,
    "trailing_approach": 80,
    "attacking_notes": 120,
    "defensive_notes": 120,
    "match_management_notes": 120,
    "set_piece_notes": 80,
}


def _item_count(value):
    if isinstance(value, (list, tuple, set)):
        return sum(bool(str(item).strip()) for item in value)
    if isinstance(value, dict):
        return sum(item not in (None, "", [], {}) for item in value.values())
    return int(bool(str(value or "").strip()))


def calculate_existing_confidence(apps, schema_editor):
    Profile = apps.get_model("catalog", "CoachTacticalProfile")
    for profile in Profile.objects.all().iterator(chunk_size=200):
        rating_score = (
            45
            * sum(getattr(profile, field) is not None for field in RATING_FIELDS)
            / len(RATING_FIELDS)
        )
        narrative_score = (
            25
            * sum(
                min(len(str(getattr(profile, field) or "").strip()) / target, 1)
                for field, target in NARRATIVE_TARGETS.items()
            )
            / len(NARRATIVE_TARGETS)
        )
        formation_score = 5 if str(profile.preferred_formation or "").strip() else 0
        formation_score += min(3, _item_count(profile.alternative_formations) * 1.5)
        scope_score = 2 if profile.effective_from else 0
        source_score = min(15, _item_count(profile.source_urls) * 5)
        review_score = 5 if profile.status == "approved" else 0
        score = round(
            min(
                100,
                rating_score
                + narrative_score
                + formation_score
                + scope_score
                + source_score
                + review_score,
            )
        )
        confidence = (
            "unknown" if score == 0 else "low" if score < 40 else "medium" if score < 70 else "high"
        )
        Profile.objects.filter(pk=profile.pk).update(confidence_score=score, confidence=confidence)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_coachprofile_coachtacticalprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachtacticalprofile",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(
                default=0,
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coachtacticalprofile",
            name="confidence",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="unknown",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.RunPython(calculate_existing_confidence, migrations.RunPython.noop),
    ]
