from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    AlgoRunViewSet,
    BackGameView,
    BackedGamesView,
    BetanoSlipImportView,
    DailyPicksDownloadView,
    DailyPicksView,
    FixtureSearchView,
    GameDetailView,
    GamesView,
    MaintenanceRunView,
    ManualSlipReviewView,
    MarketHealthView,
    PickDetailView,
    PublicRecordView,
    PublicSummaryView,
    SlipReviewDetailView,
    SlipReviewEventsView,
    SlipReviewListView,
    SlipReviewRandomizeView,
    SlipReviewStreamTokenView,
    SlipRepairView,
    SlipReviewOptionsView,
    SlipReviewRecapView,
    SportyBetSlipImportView,
    StatPalFixtureContextView,
    StatPalFixtureRefreshView,
    StatPalReadinessView,
    TaskStatusView,
    PayfonteWebhookView,
    TokenAdminAdjustmentView,
    TokenPackageListView,
    TokenPurchaseAdminCompleteView,
    TokenPurchaseAdminFailView,
    TokenPurchaseVerifyView,
    TokenPurchaseView,
    TokenTransactionListView,
    TokenWalletView,
    TopPickView,
)


router = DefaultRouter()
router.register("runs", AlgoRunViewSet, basename="algo-run")

urlpatterns = [
    path("public/summary/", PublicSummaryView.as_view(), name="algo-public-summary"),
    path("public/record/", PublicRecordView.as_view(), name="algo-public-record"),
    path("tokens/", TokenWalletView.as_view(), name="algo-token-wallet"),
    path("tokens/packages/", TokenPackageListView.as_view(), name="algo-token-packages"),
    path("tokens/purchases/", TokenPurchaseView.as_view(), name="algo-token-purchases"),
    path("tokens/payfonte/webhook/", PayfonteWebhookView.as_view(), name="algo-token-payfonte-webhook"),
    path(
        "tokens/purchases/<int:purchase_id>/admin-complete/",
        TokenPurchaseAdminCompleteView.as_view(),
        name="algo-token-purchase-admin-complete",
    ),
    path(
        "tokens/purchases/<int:purchase_id>/verify/",
        TokenPurchaseVerifyView.as_view(),
        name="algo-token-purchase-verify",
    ),
    path(
        "tokens/purchases/<int:purchase_id>/admin-fail/",
        TokenPurchaseAdminFailView.as_view(),
        name="algo-token-purchase-admin-fail",
    ),
    path("tokens/transactions/", TokenTransactionListView.as_view(), name="algo-token-transactions"),
    path("tokens/admin/adjust/", TokenAdminAdjustmentView.as_view(), name="algo-token-admin-adjust"),
    path("picks/", DailyPicksView.as_view(), name="algo-picks"),
    path("picks/download/", DailyPicksDownloadView.as_view(), name="algo-picks-download"),
    path("picks/<int:pick_id>/", PickDetailView.as_view(), name="algo-pick-detail"),
    path("fixtures/search/", FixtureSearchView.as_view(), name="algo-fixture-search"),
    path("slip-reviews/", SlipReviewListView.as_view(), name="algo-slip-reviews"),
    path("slip-reviews/options/", SlipReviewOptionsView.as_view(), name="algo-slip-review-options"),
    path("slip-reviews/recap/", SlipReviewRecapView.as_view(), name="algo-slip-review-recap"),
    path("slip-reviews/manual/", ManualSlipReviewView.as_view(), name="algo-manual-slip-review"),
    path("slip-reviews/sportybet/", SportyBetSlipImportView.as_view(), name="algo-sportybet-slip-import"),
    path("slip-reviews/betano/", BetanoSlipImportView.as_view(), name="algo-betano-slip-import"),
    path("slip-reviews/<int:review_id>/stream-token/", SlipReviewStreamTokenView.as_view(), name="algo-slip-review-stream-token"),
    path("slip-reviews/<int:review_id>/events/", SlipReviewEventsView.as_view(), name="algo-slip-review-events"),
    path("slip-reviews/<int:review_id>/randomize/", SlipReviewRandomizeView.as_view(), name="algo-slip-review-randomize"),
    path("slip-reviews/<int:review_id>/", SlipReviewDetailView.as_view(), name="algo-slip-review-detail"),
    path("slip-reviews/<int:review_id>/repair/", SlipRepairView.as_view(), name="algo-slip-review-repair"),
    path("statpal/fixtures/context/", StatPalFixtureContextView.as_view(), name="algo-statpal-fixture-context"),
    path("statpal/fixtures/refresh/", StatPalFixtureRefreshView.as_view(), name="algo-statpal-fixture-refresh"),
    path("statpal/readiness/", StatPalReadinessView.as_view(), name="algo-statpal-readiness"),
    path("games/", GamesView.as_view(), name="algo-games"),
    path("games/backed/", BackedGamesView.as_view(), name="algo-backed-games"),
    path("games/<str:match_id>/backed/", BackGameView.as_view(), name="algo-game-backed"),
    path("games/<str:match_id>/", GameDetailView.as_view(), name="algo-game-detail"),
    path("markets/health/", MarketHealthView.as_view(), name="algo-market-health"),
    path("top-picks/", TopPickView.as_view(), name="algo-top-picks"),
    path("top-pick/", TopPickView.as_view(), name="algo-top-pick"),
    path("maintenance/run/", MaintenanceRunView.as_view(), name="algo-maintenance-run"),
    path("tasks/<str:task_id>/", TaskStatusView.as_view(), name="algo-task-status"),
    path("", include(router.urls)),
]
