# Generated by Django 5.2.13 on 2026-05-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pick',
            options={'ordering': ['match_date', 'tier', '-confidence', '-ev']},
        ),
        migrations.AddField(
            model_name='pick',
            name='match_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='match_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pick',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='result',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pick',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pick',
            name='score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pick',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='stake',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('void', 'Void')], default='pending', max_length=20),
        ),
    ]
