# Generated by Django 5.2.13 on 2026-05-18 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_alter_pick_options_pick_match_date_pick_match_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='away_recent_form',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pick',
            name='away_team',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pick',
            name='home_recent_form',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pick',
            name='home_team',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pick',
            name='model_verdict',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PickBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backs', to='algo.pick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backed_picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('pick', 'user')},
            },
        ),
    ]
