# Generated by Codex on 2026-05-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo", "0004_backfill_pick_match_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPrediction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_date", models.DateField()),
                ("fixture", models.CharField(max_length=255)),
                ("home_team", models.CharField(blank=True, max_length=255)),
                ("away_team", models.CharField(blank=True, max_length=255)),
                ("league", models.CharField(blank=True, max_length=255)),
                ("kickoff", models.CharField(blank=True, max_length=50)),
                ("match_id", models.CharField(blank=True, max_length=100)),
                ("market", models.CharField(max_length=100)),
                ("meaning", models.CharField(blank=True, max_length=255)),
                ("raw_confidence", models.PositiveIntegerField(default=0)),
                ("confidence", models.PositiveIntegerField(default=0)),
                ("odds", models.DecimalField(decimal_places=2, max_digits=8)),
                ("ev", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("odds_source", models.CharField(blank=True, max_length=30)),
                ("odds_meta", models.JSONField(blank=True, default=dict)),
                ("eligible", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=False)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                ("home_recent_form", models.JSONField(blank=True, default=dict)),
                ("away_recent_form", models.JSONField(blank=True, default=dict)),
                ("fixture_context", models.JSONField(blank=True, default=dict)),
                ("team_news", models.JSONField(blank=True, default=dict)),
                ("score", models.CharField(blank=True, max_length=20)),
                ("result", models.CharField(blank=True, max_length=255)),
                ("pnl_simulated", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("win", "Win"), ("loss", "Loss"), ("void", "Void")], default="pending", max_length=20)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="market_predictions", to="algo.algorun")),
                ("selected_pick", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="internal_predictions", to="algo.pick")),
            ],
            options={
                "ordering": ["match_date", "fixture", "-confidence", "market"],
            },
        ),
        migrations.AddIndex(
            model_name="marketprediction",
            index=models.Index(fields=["match_date", "status"], name="algo_market_match_d_2a4185_idx"),
        ),
        migrations.AddIndex(
            model_name="marketprediction",
            index=models.Index(fields=["market", "status"], name="algo_market_market_5fda22_idx"),
        ),
        migrations.AddIndex(
            model_name="marketprediction",
            index=models.Index(fields=["league", "market", "status"], name="algo_market_league_111bae_idx"),
        ),
        migrations.AddIndex(
            model_name="marketprediction",
            index=models.Index(fields=["published", "status"], name="algo_market_publish_d2ec3c_idx"),
        ),
        migrations.AddIndex(
            model_name="marketprediction",
            index=models.Index(fields=["match_id", "market"], name="algo_market_match_i_ec86d7_idx"),
        ),
        migrations.AddConstraint(
            model_name="marketprediction",
            constraint=models.UniqueConstraint(fields=("run", "match_id", "fixture", "market"), name="unique_market_prediction_per_run_fixture_market"),
        ),
    ]
