# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo", "0005_marketprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketprediction",
            name="insights",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pick",
            name="insights",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
