# Generated by Django 5.2.13 on 2026-05-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0005_marketprediction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketprediction',
            new_name='algo_market_match_d_395881_idx',
            old_name='algo_market_match_d_2a4185_idx',
        ),
        migrations.RenameIndex(
            model_name='marketprediction',
            new_name='algo_market_market_ff1b97_idx',
            old_name='algo_market_market_5fda22_idx',
        ),
        migrations.RenameIndex(
            model_name='marketprediction',
            new_name='algo_market_league_42426c_idx',
            old_name='algo_market_league_111bae_idx',
        ),
        migrations.RenameIndex(
            model_name='marketprediction',
            new_name='algo_market_publish_8bd4b5_idx',
            old_name='algo_market_publish_d2ec3c_idx',
        ),
        migrations.RenameIndex(
            model_name='marketprediction',
            new_name='algo_market_match_i_8a1f8f_idx',
            old_name='algo_market_match_i_ec86d7_idx',
        ),
    ]
