# Generated by Django 5.2.13 on 2026-05-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0006_pick_marketprediction_insights'),
        ('algo', '0006_rename_algo_market_match_d_2a4185_idx_algo_market_match_d_395881_idx_and_more'),
    ]

    operations = [
    ]
