# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo", "0007_merge_20260527_2352"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_date", models.DateField(unique=True)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("markets_suppressed", models.JSONField(blank=True, default=list)),
                ("markets_cooling", models.JSONField(blank=True, default=list)),
                ("markets_promoted", models.JSONField(blank=True, default=list)),
                ("league_market_actions", models.JSONField(blank=True, default=dict)),
                ("league_warnings", models.JSONField(blank=True, default=list)),
                ("daily_policy", models.CharField(default="adaptive_market_memory", max_length=100)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-target_date"],
                "indexes": [models.Index(fields=["target_date"], name="algo_strate_target__78fbd3_idx")],
            },
        ),
    ]
