# Generated by Django 5.2.13 on 2026-05-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0008_strategyreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='strategyreview',
            new_name='algo_strate_target__f06c48_idx',
            old_name='algo_strate_target__78fbd3_idx',
        ),
    ]
