# Generated by Codex on 2026-06-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo", "0009_rename_algo_strate_target__78fbd3_idx_algo_strate_target__f06c48_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgoFixture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_date", models.DateField()),
                ("fixture", models.CharField(max_length=255)),
                ("home_team", models.CharField(blank=True, max_length=255)),
                ("away_team", models.CharField(blank=True, max_length=255)),
                ("home_logo", models.URLField(blank=True)),
                ("away_logo", models.URLField(blank=True)),
                ("league", models.CharField(blank=True, max_length=255)),
                ("league_logo", models.URLField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("country_flag", models.URLField(blank=True)),
                ("round", models.CharField(blank=True, max_length=255)),
                ("league_type", models.CharField(blank=True, max_length=50)),
                ("kickoff", models.CharField(blank=True, max_length=50)),
                ("match_id", models.CharField(max_length=100)),
                ("market_count", models.PositiveIntegerField(default=0)),
                ("markets_70_plus", models.PositiveIntegerField(default=0)),
                ("markets_65_plus", models.PositiveIntegerField(default=0)),
                ("home_recent_form", models.JSONField(blank=True, default=dict)),
                ("away_recent_form", models.JSONField(blank=True, default=dict)),
                ("fixture_context", models.JSONField(blank=True, default=dict)),
                ("team_news", models.JSONField(blank=True, default=dict)),
                ("corner_profile", models.JSONField(blank=True, default=dict)),
                ("insights", models.JSONField(blank=True, default=dict)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("scored", "Scored"), ("failed", "Failed")], default="pending", max_length=20)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fixtures", to="algo.algorun")),
            ],
            options={
                "ordering": ["match_date", "country", "league", "kickoff", "fixture"],
                "indexes": [
                    models.Index(fields=["match_date", "status"], name="algo_algofi_match_d_0120aa_idx"),
                    models.Index(fields=["run", "match_id"], name="algo_algofi_run_id_3960f5_idx"),
                    models.Index(fields=["country", "league"], name="algo_algofi_country_0d5888_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "match_id"), name="unique_algo_fixture_per_run_match"),
                ],
            },
        ),
    ]
