# Generated by Codex on 2026-06-01

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo", "0010_algofixture"),
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameBack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_id", models.CharField(max_length=100)),
                ("match_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fixture", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="backs", to="algo.algofixture")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="backed_games", to=django.conf.settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "match_date"], name="algo_gameba_user_id_9eff12_idx"),
                    models.Index(fields=["match_id"], name="algo_gameba_match_i_119779_idx"),
                ],
                "unique_together": {("user", "match_id")},
            },
        ),
    ]
