# Generated by Django 5.2.13 on 2026-06-14 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0011_gameback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameback',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameback',
            name='confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameback',
            name='ev',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='gameback',
            name='final_confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameback',
            name='market',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gameback',
            name='market_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gameback',
            name='meaning',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gameback',
            name='odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='gameback',
            index=models.Index(fields=['match_id', 'market'], name='algo_gameba_match_i_cc6cb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameback',
            constraint=models.UniqueConstraint(fields=('user', 'match_id', 'market'), name='unique_game_back_user_match_market'),
        ),
    ]
