# Generated by Django 5.2.13 on 2026-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0012_alter_gameback_unique_together_gameback_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('fixture', models.CharField(max_length=255)),
                ('home_team', models.CharField(blank=True, max_length=255)),
                ('away_team', models.CharField(blank=True, max_length=255)),
                ('home_team_normalized', models.CharField(blank=True, max_length=255)),
                ('away_team_normalized', models.CharField(blank=True, max_length=255)),
                ('fixture_normalized', models.CharField(blank=True, max_length=520)),
                ('home_logo', models.URLField(blank=True)),
                ('away_logo', models.URLField(blank=True)),
                ('league', models.CharField(blank=True, max_length=255)),
                ('league_logo', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_flag', models.URLField(blank=True)),
                ('round', models.CharField(blank=True, max_length=255)),
                ('league_type', models.CharField(blank=True, max_length=50)),
                ('kickoff', models.CharField(blank=True, max_length=50)),
                ('kickoff_utc', models.DateTimeField(blank=True, null=True)),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('api_payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='api_football', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['match_date', 'country', 'league', 'kickoff', 'fixture'],
                'indexes': [models.Index(fields=['match_date'], name='algo_fixtur_match_d_c01942_idx'), models.Index(fields=['home_team_normalized'], name='algo_fixtur_home_te_063e0e_idx'), models.Index(fields=['away_team_normalized'], name='algo_fixtur_away_te_2d86bb_idx'), models.Index(fields=['fixture_normalized'], name='algo_fixtur_fixture_d3bf86_idx'), models.Index(fields=['country', 'league'], name='algo_fixtur_country_7456b5_idx')],
            },
        ),
    ]
