# Generated by Django 5.2.13 on 2026-07-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0013_fixturecache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlipReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('sportybet', 'SportyBet'), ('betano', 'Betano')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='completed', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('submitted_payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlipSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('submitted_match', models.CharField(max_length=255)),
                ('submitted_market', models.CharField(max_length=120)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('verdict', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('match_id', models.CharField(blank=True, max_length=100)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('fixture', models.CharField(blank=True, max_length=255)),
                ('home_team', models.CharField(blank=True, max_length=255)),
                ('away_team', models.CharField(blank=True, max_length=255)),
                ('league', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('kickoff', models.CharField(blank=True, max_length=50)),
                ('selected_market', models.JSONField(blank=True, default=dict)),
                ('best_market', models.JSONField(blank=True, default=dict)),
                ('recommended_market', models.JSONField(blank=True, default=dict)),
                ('possible_matches', models.JSONField(blank=True, default=list)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='algo.slipreview')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='slipreview',
            index=models.Index(fields=['user', 'created_at'], name='algo_slipre_user_id_b978ba_idx'),
        ),
        migrations.AddIndex(
            model_name='slipreview',
            index=models.Index(fields=['source', 'status'], name='algo_slipre_source_b40ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='slipselection',
            index=models.Index(fields=['review', 'order'], name='algo_slipse_review__071346_idx'),
        ),
        migrations.AddIndex(
            model_name='slipselection',
            index=models.Index(fields=['match_id'], name='algo_slipse_match_i_29f60d_idx'),
        ),
        migrations.AddIndex(
            model_name='slipselection',
            index=models.Index(fields=['status', 'verdict'], name='algo_slipse_status_39798d_idx'),
        ),
    ]
