# Generated by Django 5.2.13 on 2026-07-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0014_slipreview_slipselection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slipreview',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('importing', 'Importing'), ('analysing', 'Analysing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='completed', max_length=30),
        ),
    ]
