# Generated by Django 5.2.13 on 2026-07-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0015_alter_slipreview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmakerLeagueMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('provider_competition_id', models.CharField(blank=True, max_length=100)),
                ('provider_competition_name', models.CharField(max_length=255)),
                ('provider_competition_normalized', models.CharField(blank=True, max_length=255)),
                ('api_league_id', models.PositiveIntegerField()),
                ('api_league_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('current_api_season', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(default='auto', max_length=50)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'provider_competition_name'],
                'indexes': [models.Index(fields=['provider', 'provider_competition_id'], name='algo_bookma_provide_018943_idx'), models.Index(fields=['provider', 'provider_competition_normalized'], name='algo_bookma_provide_d3f2ec_idx'), models.Index(fields=['api_league_id'], name='algo_bookma_api_lea_44fdcd_idx'), models.Index(fields=['active'], name='algo_bookma_active_89139c_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_competition_id', 'provider_competition_normalized'), name='unique_bookmaker_league_map_provider_competition')],
            },
        ),
        migrations.CreateModel(
            name='ProviderFixtureMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('provider_event_id', models.CharField(max_length=120)),
                ('provider_competition_id', models.CharField(blank=True, max_length=100)),
                ('provider_competition_name', models.CharField(blank=True, max_length=255)),
                ('api_fixture_id', models.CharField(max_length=100)),
                ('api_league_id', models.PositiveIntegerField(blank=True, null=True)),
                ('api_league_name', models.CharField(blank=True, max_length=255)),
                ('provider_home_team', models.CharField(blank=True, max_length=255)),
                ('provider_away_team', models.CharField(blank=True, max_length=255)),
                ('api_home_team', models.CharField(blank=True, max_length=255)),
                ('api_away_team', models.CharField(blank=True, max_length=255)),
                ('kickoff_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('resolution_method', models.CharField(default='team_date_league', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'provider_event_id'],
                'indexes': [models.Index(fields=['provider', 'provider_event_id'], name='algo_provid_provide_48016a_idx'), models.Index(fields=['api_fixture_id'], name='algo_provid_api_fix_877336_idx'), models.Index(fields=['provider_competition_id'], name='algo_provid_provide_af8d6e_idx'), models.Index(fields=['active'], name='algo_provid_active_16b984_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_provider_fixture_map_event')],
            },
        ),
        migrations.CreateModel(
            name='TeamAliasMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('api_team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('canonical_name', models.CharField(max_length=255)),
                ('canonical_normalized', models.CharField(blank=True, max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('alias_normalized', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(default='auto', max_length=50)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['alias'],
                'indexes': [models.Index(fields=['provider', 'alias_normalized'], name='algo_teamal_provide_37fb06_idx'), models.Index(fields=['api_team_id'], name='algo_teamal_api_tea_60eb71_idx'), models.Index(fields=['canonical_normalized'], name='algo_teamal_canonic_857422_idx'), models.Index(fields=['active'], name='algo_teamal_active_3d3ef8_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'alias_normalized', 'canonical_normalized'), name='unique_team_alias_provider_alias_canonical')],
            },
        ),
    ]
