# Generated by Django 5.2.13 on 2026-08-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0016_bookmakerleaguemap_providerfixturemap_teamaliasmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPlayerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('provider_player_id', models.CharField(max_length=120)),
                ('provider_player_name', models.CharField(max_length=255)),
                ('provider_player_normalized', models.CharField(blank=True, max_length=255)),
                ('internal_player_id', models.CharField(blank=True, max_length=120)),
                ('internal_player_name', models.CharField(blank=True, max_length=255)),
                ('internal_player_normalized', models.CharField(blank=True, max_length=255)),
                ('provider_team_id', models.CharField(blank=True, max_length=120)),
                ('provider_team_name', models.CharField(blank=True, max_length=255)),
                ('internal_team_id', models.CharField(blank=True, max_length=120)),
                ('internal_team_name', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=80)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('resolution_method', models.CharField(default='provider_id', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'provider_player_name'],
                'indexes': [models.Index(fields=['provider', 'provider_player_id'], name='algo_provid_provide_6ced3d_idx'), models.Index(fields=['provider', 'provider_player_normalized'], name='algo_provid_provide_01c6dd_idx'), models.Index(fields=['internal_player_id'], name='algo_provid_interna_c2567c_idx'), models.Index(fields=['provider_team_id'], name='algo_provid_provide_1db07c_idx'), models.Index(fields=['active'], name='algo_provid_active_1c4270_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_player_id'), name='unique_provider_player_map_provider_player')],
            },
        ),
        migrations.CreateModel(
            name='ProviderTeamMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('provider_team_id', models.CharField(max_length=120)),
                ('provider_team_name', models.CharField(max_length=255)),
                ('provider_team_normalized', models.CharField(blank=True, max_length=255)),
                ('internal_team_id', models.CharField(blank=True, max_length=120)),
                ('internal_team_name', models.CharField(blank=True, max_length=255)),
                ('internal_team_normalized', models.CharField(blank=True, max_length=255)),
                ('api_team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('resolution_method', models.CharField(default='provider_id', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'provider_team_name'],
                'indexes': [models.Index(fields=['provider', 'provider_team_id'], name='algo_provid_provide_127630_idx'), models.Index(fields=['provider', 'provider_team_normalized'], name='algo_provid_provide_8b6700_idx'), models.Index(fields=['internal_team_id'], name='algo_provid_interna_59c9e2_idx'), models.Index(fields=['api_team_id'], name='algo_provid_api_tea_f485fe_idx'), models.Index(fields=['active'], name='algo_provid_active_20ff1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_team_id'), name='unique_provider_team_map_provider_team')],
            },
        ),
    ]
