# Generated by Django 5.2.13 on 2026-08-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0017_providerplayermap_providerteammap'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatPalFixtureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(blank=True, max_length=120)),
                ('provider_match_id', models.CharField(blank=True, max_length=120)),
                ('provider_competition_id', models.CharField(blank=True, max_length=100)),
                ('snapshot_type', models.CharField(choices=[('injuries_suspensions', 'Injuries & Suspensions'), ('team_stats', 'Team Stats'), ('prematch_odds', 'Pre-Match Odds'), ('live_odds', 'Live Odds'), ('lineups', 'Lineups'), ('predictions', 'Predictions'), ('detailed_stats', 'Detailed Stats'), ('raw', 'Raw')], max_length=40)),
                ('source_endpoint', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(default='available', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statpal_snapshots', to='algo.fixturecache')),
                ('provider_fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statpal_snapshots', to='algo.providerfixturemap')),
            ],
            options={
                'ordering': ['-fetched_at', '-updated_at'],
                'indexes': [models.Index(fields=['match_id', 'snapshot_type'], name='algo_statpa_match_i_d90ef4_idx'), models.Index(fields=['provider_match_id', 'snapshot_type'], name='algo_statpa_provide_46898f_idx'), models.Index(fields=['provider_competition_id', 'snapshot_type'], name='algo_statpa_provide_575a02_idx'), models.Index(fields=['snapshot_type', 'status'], name='algo_statpa_snapsho_5fc3c0_idx'), models.Index(fields=['expires_at'], name='algo_statpa_expires_391f29_idx')],
                'constraints': [models.UniqueConstraint(fields=('match_id', 'provider_match_id', 'snapshot_type'), name='unique_statpal_snapshot_fixture_type')],
            },
        ),
    ]
