# Generated by Django 5.2.13 on 2026-08-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0018_statpalfixturesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipselection',
            name='flagged_risky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slipselection',
            name='odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='slipselection',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('void', 'Void'), ('unsettleable', 'Unsettleable')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='slipselection',
            name='result',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='slipselection',
            name='score',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='slipselection',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slipselection',
            name='settlement_market',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='slipreview',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('importing', 'Importing'), ('analysing', 'Analysing'), ('completed', 'Completed'), ('partial', 'Partial'), ('unanalysed', 'Unanalysed'), ('failed', 'Failed')], default='completed', max_length=30),
        ),
        migrations.AddIndex(
            model_name='slipselection',
            index=models.Index(fields=['outcome', 'match_date'], name='algo_slipse_outcome_d3f4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='slipselection',
            index=models.Index(fields=['review', 'outcome'], name='algo_slipse_review__af2256_idx'),
        ),
    ]
