# Generated by Django 5.2.13 on 2026-08-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0019_slipselection_flagged_risky_slipselection_odds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipselection',
            name='advisory_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
