# Generated by Django 5.2.13 on 2026-08-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0020_slipselection_advisory_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='statpal', max_length=30)),
                ('league_id', models.CharField(max_length=64)),
                ('league_name', models.CharField(blank=True, max_length=255)),
                ('season', models.CharField(blank=True, max_length=32)),
                ('model_version', models.CharField(max_length=32)),
                ('home_goal_baseline', models.FloatField(default=1.35)),
                ('away_goal_baseline', models.FloatField(default=1.1)),
                ('rho', models.FloatField(default=-0.13)),
                ('data_quality', models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('limited', 'Limited'), ('poor', 'Poor')], default='poor', max_length=20)),
                ('teams_fitted', models.PositiveIntegerField(default=0)),
                ('matches_observed', models.PositiveIntegerField(default=0)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('fitted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fitted_at'],
                'indexes': [models.Index(fields=['provider', 'league_id'], name='algo_league_provide_54ffb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'league_id', 'model_version'), name='unique_league_score_model')],
            },
        ),
        migrations.CreateModel(
            name='TeamStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, max_length=64)),
                ('team_name', models.CharField(max_length=255)),
                ('team_name_normalized', models.CharField(db_index=True, max_length=255)),
                ('home_attack', models.FloatField(default=1.0)),
                ('home_defence', models.FloatField(default=1.0)),
                ('away_attack', models.FloatField(default=1.0)),
                ('away_defence', models.FloatField(default=1.0)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('shots_per_game', models.FloatField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='algo.leaguescoremodel')),
            ],
            options={
                'indexes': [models.Index(fields=['model', 'team_name_normalized'], name='algo_teamst_model_i_1eaefa_idx'), models.Index(fields=['model', 'team_id'], name='algo_teamst_model_i_9e8882_idx')],
            },
        ),
    ]
