# Generated by Django 5.2.13 on 2026-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0021_leaguescoremodel_teamstrength'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='statpal', max_length=30)),
                ('team_id', models.CharField(max_length=64)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('team_name_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('league_id', models.CharField(blank=True, max_length=64)),
                ('corners_home', models.FloatField(blank=True, null=True)),
                ('corners_away', models.FloatField(blank=True, null=True)),
                ('cards_home', models.FloatField(blank=True, null=True)),
                ('cards_away', models.FloatField(blank=True, null=True)),
                ('fouls_per_game', models.FloatField(blank=True, null=True)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'team_name_normalized'], name='algo_teamra_provide_e1fb43_idx'), models.Index(fields=['league_id'], name='algo_teamra_league__661842_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'team_id'), name='unique_team_rate_profile')],
            },
        ),
    ]
