# Generated by Django 5.2.13 on 2026-08-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0022_teamrateprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlipRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('recommended', 'Recommended'), ('custom', 'Custom')], default='recommended', max_length=20)),
                ('original_legs', models.PositiveIntegerField(default=0)),
                ('original_combined_odds', models.FloatField(blank=True, null=True)),
                ('original_success_percent', models.FloatField(blank=True, null=True)),
                ('revised_legs', models.PositiveIntegerField(default=0)),
                ('revised_combined_odds', models.FloatField(blank=True, null=True)),
                ('revised_success_percent', models.FloatField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='algo.slipreview')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review', 'created_at'], name='algo_slipre_review__57e760_idx')],
            },
        ),
    ]
