# Generated by Django 5.2.13 on 2026-08-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0023_sliprepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='statpal', max_length=30)),
                ('player_id', models.CharField(blank=True, max_length=64)),
                ('player_name', models.CharField(max_length=255)),
                ('player_name_normalized', models.CharField(db_index=True, max_length=255)),
                ('team_id', models.CharField(blank=True, max_length=64)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('team_name_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('match_id', models.CharField(blank=True, max_length=64)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('out', 'Out'), ('doubtful', 'Doubtful')], default='out', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['player_name_normalized', 'match_id'], name='algo_player_player__d6ee57_idx'), models.Index(fields=['team_name_normalized', 'match_date'], name='algo_player_team_na_82f23b_idx')],
            },
        ),
    ]
