# Generated by Django 5.2.13 on 2026-08-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0024_playeravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='statpal', max_length=30)),
                ('match_id', models.CharField(max_length=64)),
                ('side', models.CharField(max_length=10)),
                ('team_id', models.CharField(blank=True, max_length=64)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('team_name_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('formation', models.CharField(blank=True, max_length=32)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('starting_xi', models.JSONField(blank=True, default=list)),
                ('bench', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['match_id', 'side'], name='algo_fixtur_match_i_44ab7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'match_id', 'side'), name='unique_fixture_lineup')],
            },
        ),
    ]
