# Generated by Django 5.2.13 on 2026-08-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0029_slipreviewstreamtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlipReviewMarketCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_scope', models.CharField(choices=[('slip_review', 'Slip Review')], default='slip_review', max_length=30)),
                ('source', models.CharField(choices=[('statpal', 'StatPal'), ('api_football', 'API-Football'), ('merged', 'Merged'), ('on_demand', 'On Demand')], default='merged', max_length=30)),
                ('match_date', models.DateField()),
                ('fixture', models.CharField(max_length=255)),
                ('home_team', models.CharField(blank=True, max_length=255)),
                ('away_team', models.CharField(blank=True, max_length=255)),
                ('home_logo', models.URLField(blank=True)),
                ('away_logo', models.URLField(blank=True)),
                ('league', models.CharField(blank=True, max_length=255)),
                ('league_id', models.CharField(blank=True, max_length=100)),
                ('league_logo', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_flag', models.URLField(blank=True)),
                ('kickoff', models.CharField(blank=True, max_length=50)),
                ('match_id', models.CharField(max_length=100)),
                ('provider_match_id', models.CharField(blank=True, max_length=120)),
                ('provider_competition_id', models.CharField(blank=True, max_length=120)),
                ('home_team_id', models.CharField(blank=True, max_length=120)),
                ('away_team_id', models.CharField(blank=True, max_length=120)),
                ('market', models.CharField(max_length=120)),
                ('market_family', models.CharField(blank=True, max_length=80)),
                ('meaning', models.CharField(blank=True, max_length=255)),
                ('raw_confidence', models.PositiveIntegerField(default=0)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('final_confidence', models.FloatField(blank=True, null=True)),
                ('odds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ev', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('odds_source', models.CharField(blank=True, max_length=30)),
                ('odds_meta', models.JSONField(blank=True, default=dict)),
                ('eligible', models.BooleanField(default=False)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('insights', models.JSONField(blank=True, default=dict)),
                ('market_payload', models.JSONField(blank=True, default=dict)),
                ('fixture_payload', models.JSONField(blank=True, default=dict)),
                ('provider_merge', models.JSONField(blank=True, default=dict)),
                ('data_quality', models.CharField(blank=True, max_length=30)),
                ('cache_version', models.CharField(blank=True, max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['match_date', 'fixture', '-confidence', 'market'],
            },
        ),
        migrations.AddIndex(
            model_name='slipreviewmarketcache',
            index=models.Index(fields=['cache_scope', 'match_date'], name='algo_slipre_cache_s_74efeb_idx'),
        ),
        migrations.AddIndex(
            model_name='slipreviewmarketcache',
            index=models.Index(fields=['cache_scope', 'match_id', 'market'], name='algo_slipre_cache_s_d499d7_idx'),
        ),
        migrations.AddIndex(
            model_name='slipreviewmarketcache',
            index=models.Index(fields=['cache_scope', 'provider_match_id', 'market'], name='algo_slipre_cache_s_d5beaa_idx'),
        ),
        migrations.AddIndex(
            model_name='slipreviewmarketcache',
            index=models.Index(fields=['cache_scope', 'league_id', 'match_date'], name='algo_slipre_cache_s_2aaf55_idx'),
        ),
        migrations.AddIndex(
            model_name='slipreviewmarketcache',
            index=models.Index(fields=['cache_scope', 'market_family', 'confidence'], name='algo_slipre_cache_s_e2d33d_idx'),
        ),
        migrations.AddIndex(
            model_name='slipreviewmarketcache',
            index=models.Index(fields=['expires_at'], name='algo_slipre_expires_88da06_idx'),
        ),
        migrations.AddConstraint(
            model_name='slipreviewmarketcache',
            constraint=models.UniqueConstraint(fields=('cache_scope', 'match_id', 'market'), name='unique_slip_review_market_cache_match_market'),
        ),
    ]
