# Generated by Codex on 2026-08-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo", "0030_slipreviewmarketcache_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenWallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("free_tokens", models.PositiveIntegerField(default=0)),
                ("paid_tokens", models.PositiveIntegerField(default=0)),
                ("last_free_refill_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TokenTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField(help_text="Positive credits tokens; negative debits tokens.")),
                ("free_tokens_delta", models.IntegerField(default=0)),
                ("paid_tokens_delta", models.IntegerField(default=0)),
                (
                    "token_bucket",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid"), ("mixed", "Mixed")],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("daily_free_refill", "Daily Free Refill"),
                            ("token_purchase_credit", "Token Purchase Credit"),
                            ("slip_review_reserve", "Slip Review Reserve"),
                            ("slip_review_consume", "Slip Review Consume"),
                            ("slip_review_release", "Slip Review Release"),
                            ("token_reservation_expire", "Token Reservation Expire"),
                            ("smart_randomize_charge", "Smart Randomize Charge"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("reference_type", models.CharField(blank=True, max_length=80)),
                ("reference_id", models.CharField(blank=True, max_length=120)),
                ("balance_after", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="algo.tokenwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TokenReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField()),
                ("free_tokens_reserved", models.PositiveIntegerField(default=0)),
                ("paid_tokens_reserved", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("reference_type", models.CharField(blank=True, max_length=80)),
                ("reference_id", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="algo.tokenwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="tokenwallet",
            index=models.Index(fields=["user"], name="algo_tokenw_user_id_a075d4_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenwallet",
            index=models.Index(fields=["last_free_refill_date"], name="algo_tokenw_last_fr_8b467c_idx"),
        ),
        migrations.AddIndex(
            model_name="tokentransaction",
            index=models.Index(fields=["user", "created_at"], name="algo_tokent_user_id_f2f456_idx"),
        ),
        migrations.AddIndex(
            model_name="tokentransaction",
            index=models.Index(fields=["reference_type", "reference_id"], name="algo_tokent_referen_844759_idx"),
        ),
        migrations.AddIndex(
            model_name="tokentransaction",
            index=models.Index(fields=["reason", "created_at"], name="algo_tokent_reason_0318f1_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenreservation",
            index=models.Index(fields=["user", "status"], name="algo_tokenr_user_id_4605d0_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenreservation",
            index=models.Index(fields=["reference_type", "reference_id"], name="algo_tokenr_referen_32a438_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenreservation",
            index=models.Index(fields=["status", "expires_at"], name="algo_tokenr_status__c5782f_idx"),
        ),
    ]
