# Generated by Codex on 2026-08-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo", "0031_tokenwallet_tokentransaction_tokenreservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("package_id", models.CharField(max_length=120)),
                ("tokens", models.PositiveIntegerField()),
                ("amount", models.PositiveIntegerField(help_text="Major currency unit, e.g. naira.")),
                ("amount_kobo", models.PositiveIntegerField()),
                ("currency", models.CharField(default="NGN", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credited_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credited_token_purchases",
                        to="algo.tokentransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="tokenpurchase",
            index=models.Index(fields=["user", "status"], name="algo_tokenp_user_id_80d2d6_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenpurchase",
            index=models.Index(fields=["package_id", "status"], name="algo_tokenp_package_3e1f55_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenpurchase",
            index=models.Index(fields=["provider", "provider_reference"], name="algo_tokenp_prov_4f3a41_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenpurchase",
            index=models.Index(fields=["status", "created_at"], name="algo_tokenp_status_3916fd_idx"),
        ),
    ]
