# Generated by Django 5.2.13 on 2026-08-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0032_tokenpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='reason',
            field=models.CharField(choices=[('signup_grant', 'Signup Grant'), ('daily_free_refill', 'Daily Free Refill'), ('token_purchase_credit', 'Token Purchase Credit'), ('slip_review_reserve', 'Slip Review Reserve'), ('slip_review_consume', 'Slip Review Consume'), ('slip_review_release', 'Slip Review Release'), ('token_reservation_expire', 'Token Reservation Expire'), ('smart_randomize_charge', 'Smart Randomize Charge'), ('admin_adjustment', 'Admin Adjustment')], max_length=40),
        ),
    ]
