# Generated by Django 5.2.13 on 2026-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0033_token_signup_grant_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguescoremodel',
            name='prior_season',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='teamstrength',
            name='prior_matches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstrength',
            name='prior_season',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
