# Generated by Django 5.2.13 on 2026-05-05 00:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrollsnapshot',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
