# Generated by Django 5.2.13 on 2026-08-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_content_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyActionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateField()),
                ('evaluated_from', models.DateField()),
                ('evaluated_to', models.DateField()),
                ('scope', models.CharField(choices=[('market', 'Market'), ('league_market', 'League Market'), ('confidence_band', 'Confidence Band')], max_length=40)),
                ('action', models.CharField(choices=[('promote', 'Promote'), ('cool', 'Cool'), ('suppress', 'Suppress')], max_length=20)),
                ('key', models.CharField(max_length=240)),
                ('market', models.CharField(blank=True, max_length=160)),
                ('league', models.CharField(blank=True, max_length=160)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('voids', models.PositiveIntegerField(default=0)),
                ('hit_rate', models.FloatField(blank=True, null=True)),
                ('roi', models.FloatField(blank=True, null=True)),
                ('baseline_roi', models.FloatField(blank=True, null=True)),
                ('roi_delta', models.FloatField(blank=True, null=True)),
                ('authority_multiplier', models.FloatField(default=1.0)),
                ('verdict', models.CharField(default='insufficient_sample', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_strategyactionoutcome',
                'ordering': ['-decision_date', 'scope', 'key'],
                'indexes': [models.Index(fields=['decision_date', 'scope'], name='strat_outcome_date_scope_idx'), models.Index(fields=['action', 'verdict'], name='strategy_outcome_action_idx'), models.Index(fields=['market'], name='strategy_outcome_market_idx'), models.Index(fields=['league', 'market'], name='strat_outcome_league_mkt_idx')],
                'constraints': [models.UniqueConstraint(fields=('decision_date', 'scope', 'action', 'key'), name='unique_strategy_action_outcome')],
            },
        ),
    ]
