# Generated by Django 5.2.13 on 2026-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('scope', models.CharField(choices=[('picks', 'Daily picks'), ('slips', 'Slip selections')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped (already running)')], default='running', max_length=10)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settlement_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['target_date', 'scope'], name='settlement__target__3ed12c_idx'), models.Index(fields=['status', 'started_at'], name='settlement__status_2c2dd9_idx')],
            },
        ),
    ]
